/*
 * This file is generated by jOOQ.
 */
package com.mt.quarkus.model.records;


import java.time.LocalDateTime;
import java.util.UUID;

import com.mt.quarkus.model.enums.CampaignsEmailThreads;
import com.mt.quarkus.model.enums.CampaignsIsFavourite;
import com.mt.quarkus.model.enums.CampaignsStatus;
import com.mt.quarkus.model.tables.Campaigns;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;



/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignsRecord extends UpdatableRecordImpl<CampaignsRecord> implements Record17<ULong, UUID, ULong, ULong, ULong, String, String, CampaignsStatus, CampaignsIsFavourite, CampaignsEmailThreads, String, String, LocalDateTime, LocalDateTime, JSON, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.id</code>.
     */
    public CampaignsRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.uid</code>.
     */
    public CampaignsRecord setUid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.uid</code>.
     */
    public UUID getUid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.user_id</code>.
     */
    public CampaignsRecord setUserId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.team_id</code>.
     */
    public CampaignsRecord setTeamId(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.team_id</code>.
     */
    public ULong getTeamId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.agency_id</code>.
     */
    public CampaignsRecord setAgencyId(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.agency_id</code>.
     */
    public ULong getAgencyId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.title</code>.
     */
    public CampaignsRecord setTitle(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.title</code>.
     */
    public String getTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.timezone</code>.
     */
    public CampaignsRecord setTimezone(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.timezone</code>.
     */
    public String getTimezone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.status</code>.
     */
    public CampaignsRecord setStatus(CampaignsStatus value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.status</code>.
     */
    public CampaignsStatus getStatus() {
        return (CampaignsStatus) get(7);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.is_favourite</code>.
     */
    public CampaignsRecord setIsFavourite(CampaignsIsFavourite value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.is_favourite</code>.
     */
    public CampaignsIsFavourite getIsFavourite() {
        return (CampaignsIsFavourite) get(8);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.email_threads</code>.
     */
    public CampaignsRecord setEmailThreads(CampaignsEmailThreads value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.email_threads</code>.
     */
    public CampaignsEmailThreads getEmailThreads() {
        return (CampaignsEmailThreads) get(9);
    }

    /**
     * Setter for
     * <code>bulk_email_tenant_01.campaigns.common_email_subject</code>.
     */
    public CampaignsRecord setCommonEmailSubject(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>bulk_email_tenant_01.campaigns.common_email_subject</code>.
     */
    public String getCommonEmailSubject() {
        return (String) get(10);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.api_key</code>.
     */
    public CampaignsRecord setApiKey(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.api_key</code>.
     */
    public String getApiKey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.start_time</code>.
     */
    public CampaignsRecord setStartTime(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.pause_time</code>.
     */
    public CampaignsRecord setPauseTime(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.pause_time</code>.
     */
    public LocalDateTime getPauseTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.setting_infos</code>.
     * carry_on_campaign Yes,No DEFAULT Yes,prevent_previous_followup Yes ,No
     * DEFAULT Yes,sent_immediate_after_resume Yes,No DEFAULT
     * Yes,is_continue_after_fail Yes,No DEFAULT Yes,real_campaign Yes,No
     * DEFAULT Yes,edit_warning_close DEFAULT No
     */
    public CampaignsRecord setSettingInfos(JSON value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.setting_infos</code>.
     * carry_on_campaign Yes,No DEFAULT Yes,prevent_previous_followup Yes ,No
     * DEFAULT Yes,sent_immediate_after_resume Yes,No DEFAULT
     * Yes,is_continue_after_fail Yes,No DEFAULT Yes,real_campaign Yes,No
     * DEFAULT Yes,edit_warning_close DEFAULT No
     */
    public JSON getSettingInfos() {
        return (JSON) get(14);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.created_at</code>.
     */
    public CampaignsRecord setCreatedAt(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>bulk_email_tenant_01.campaigns.updated_at</code>.
     */
    public CampaignsRecord setUpdatedAt(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>bulk_email_tenant_01.campaigns.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<ULong, UUID, ULong, ULong, ULong, String, String, CampaignsStatus, CampaignsIsFavourite, CampaignsEmailThreads, String, String, LocalDateTime, LocalDateTime, JSON, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<ULong, UUID, ULong, ULong, ULong, String, String, CampaignsStatus, CampaignsIsFavourite, CampaignsEmailThreads, String, String, LocalDateTime, LocalDateTime, JSON, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Campaigns.CAMPAIGNS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Campaigns.CAMPAIGNS.UID;
    }

    @Override
    public Field<ULong> field3() {
        return Campaigns.CAMPAIGNS.USER_ID;
    }

    @Override
    public Field<ULong> field4() {
        return Campaigns.CAMPAIGNS.TEAM_ID;
    }

    @Override
    public Field<ULong> field5() {
        return Campaigns.CAMPAIGNS.AGENCY_ID;
    }

    @Override
    public Field<String> field6() {
        return Campaigns.CAMPAIGNS.TITLE;
    }

    @Override
    public Field<String> field7() {
        return Campaigns.CAMPAIGNS.TIMEZONE;
    }

    @Override
    public Field<CampaignsStatus> field8() {
        return Campaigns.CAMPAIGNS.STATUS;
    }

    @Override
    public Field<CampaignsIsFavourite> field9() {
        return Campaigns.CAMPAIGNS.IS_FAVOURITE;
    }

    @Override
    public Field<CampaignsEmailThreads> field10() {
        return Campaigns.CAMPAIGNS.EMAIL_THREADS;
    }

    @Override
    public Field<String> field11() {
        return Campaigns.CAMPAIGNS.COMMON_EMAIL_SUBJECT;
    }

    @Override
    public Field<String> field12() {
        return Campaigns.CAMPAIGNS.API_KEY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Campaigns.CAMPAIGNS.START_TIME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return Campaigns.CAMPAIGNS.PAUSE_TIME;
    }

    @Override
    public Field<JSON> field15() {
        return Campaigns.CAMPAIGNS.SETTING_INFOS;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Campaigns.CAMPAIGNS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return Campaigns.CAMPAIGNS.UPDATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUid();
    }

    @Override
    public ULong component3() {
        return getUserId();
    }

    @Override
    public ULong component4() {
        return getTeamId();
    }

    @Override
    public ULong component5() {
        return getAgencyId();
    }

    @Override
    public String component6() {
        return getTitle();
    }

    @Override
    public String component7() {
        return getTimezone();
    }

    @Override
    public CampaignsStatus component8() {
        return getStatus();
    }

    @Override
    public CampaignsIsFavourite component9() {
        return getIsFavourite();
    }

    @Override
    public CampaignsEmailThreads component10() {
        return getEmailThreads();
    }

    @Override
    public String component11() {
        return getCommonEmailSubject();
    }

    @Override
    public String component12() {
        return getApiKey();
    }

    @Override
    public LocalDateTime component13() {
        return getStartTime();
    }

    @Override
    public LocalDateTime component14() {
        return getPauseTime();
    }

    @Override
    public JSON component15() {
        return getSettingInfos();
    }

    @Override
    public LocalDateTime component16() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component17() {
        return getUpdatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUid();
    }

    @Override
    public ULong value3() {
        return getUserId();
    }

    @Override
    public ULong value4() {
        return getTeamId();
    }

    @Override
    public ULong value5() {
        return getAgencyId();
    }

    @Override
    public String value6() {
        return getTitle();
    }

    @Override
    public String value7() {
        return getTimezone();
    }

    @Override
    public CampaignsStatus value8() {
        return getStatus();
    }

    @Override
    public CampaignsIsFavourite value9() {
        return getIsFavourite();
    }

    @Override
    public CampaignsEmailThreads value10() {
        return getEmailThreads();
    }

    @Override
    public String value11() {
        return getCommonEmailSubject();
    }

    @Override
    public String value12() {
        return getApiKey();
    }

    @Override
    public LocalDateTime value13() {
        return getStartTime();
    }

    @Override
    public LocalDateTime value14() {
        return getPauseTime();
    }

    @Override
    public JSON value15() {
        return getSettingInfos();
    }

    @Override
    public LocalDateTime value16() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value17() {
        return getUpdatedAt();
    }

    @Override
    public CampaignsRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public CampaignsRecord value2(UUID value) {
        setUid(value);
        return this;
    }

    @Override
    public CampaignsRecord value3(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public CampaignsRecord value4(ULong value) {
        setTeamId(value);
        return this;
    }

    @Override
    public CampaignsRecord value5(ULong value) {
        setAgencyId(value);
        return this;
    }

    @Override
    public CampaignsRecord value6(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public CampaignsRecord value7(String value) {
        setTimezone(value);
        return this;
    }

    @Override
    public CampaignsRecord value8(CampaignsStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public CampaignsRecord value9(CampaignsIsFavourite value) {
        setIsFavourite(value);
        return this;
    }

    @Override
    public CampaignsRecord value10(CampaignsEmailThreads value) {
        setEmailThreads(value);
        return this;
    }

    @Override
    public CampaignsRecord value11(String value) {
        setCommonEmailSubject(value);
        return this;
    }

    @Override
    public CampaignsRecord value12(String value) {
        setApiKey(value);
        return this;
    }

    @Override
    public CampaignsRecord value13(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public CampaignsRecord value14(LocalDateTime value) {
        setPauseTime(value);
        return this;
    }

    @Override
    public CampaignsRecord value15(JSON value) {
        setSettingInfos(value);
        return this;
    }

    @Override
    public CampaignsRecord value16(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CampaignsRecord value17(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CampaignsRecord values(ULong value1, UUID value2, ULong value3, ULong value4, ULong value5, String value6, String value7, CampaignsStatus value8, CampaignsIsFavourite value9, CampaignsEmailThreads value10, String value11, String value12, LocalDateTime value13, LocalDateTime value14, JSON value15, LocalDateTime value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignsRecord
     */
    public CampaignsRecord() {
        super(Campaigns.CAMPAIGNS);
    }

    /**
     * Create a detached, initialised CampaignsRecord
     */
    public CampaignsRecord(ULong id, UUID uid, ULong userId, ULong teamId, ULong agencyId, String title, String timezone, CampaignsStatus status, CampaignsIsFavourite isFavourite, CampaignsEmailThreads emailThreads, String commonEmailSubject, String apiKey, LocalDateTime startTime, LocalDateTime pauseTime, JSON settingInfos, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Campaigns.CAMPAIGNS);

        setId(id);
        setUid(uid);
        setUserId(userId);
        setTeamId(teamId);
        setAgencyId(agencyId);
        setTitle(title);
        setTimezone(timezone);
        setStatus(status);
        setIsFavourite(isFavourite);
        setEmailThreads(emailThreads);
        setCommonEmailSubject(commonEmailSubject);
        setApiKey(apiKey);
        setStartTime(startTime);
        setPauseTime(pauseTime);
        setSettingInfos(settingInfos);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised CampaignsRecord
     */
    public CampaignsRecord(com.mt.quarkus.model.tables.pojos.Campaigns value) {
        super(Campaigns.CAMPAIGNS);

        if (value != null) {
            setId(value.getId());
            setUid(value.getUid());
            setUserId(value.getUserId());
            setTeamId(value.getTeamId());
            setAgencyId(value.getAgencyId());
            setTitle(value.getTitle());
            setTimezone(value.getTimezone());
            setStatus(value.getStatus());
            setIsFavourite(value.getIsFavourite());
            setEmailThreads(value.getEmailThreads());
            setCommonEmailSubject(value.getCommonEmailSubject());
            setApiKey(value.getApiKey());
            setStartTime(value.getStartTime());
            setPauseTime(value.getPauseTime());
            setSettingInfos(value.getSettingInfos());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
