/*
 * This file is generated by jOOQ.
 */
package com.mt.quarkus.model.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CampaignsIsFavourite implements EnumType {

    YES("YES"),

    NO("NO");

    private final String literal;

    private CampaignsIsFavourite(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "campaigns_is_favourite";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static CampaignsIsFavourite lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CampaignsIsFavourite.class, literal);
    }
}
