/*
 * This file is generated by jOOQ.
 */
package com.mt.quarkus.model.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CampaignsEmailThreads implements EnumType {

    SINGLE_THREAD("SINGLE_THREAD"),

    MULTI_THREAD("MULTI_THREAD");

    private final String literal;

    private CampaignsEmailThreads(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "campaigns_email_threads";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static CampaignsEmailThreads lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CampaignsEmailThreads.class, literal);
    }
}
