/*
 * This file is generated by jOOQ.
 */
package com.mt.quarkus.model;

/**
 * A class modelling indexes of tables in bulk_email_tenant_01.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

}
