/*
 * This file is generated by jOOQ.
 */
package com.mt.quarkus.model;


import com.mt.quarkus.model.records.CampaignsRecord;
import com.mt.quarkus.model.tables.Campaigns;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * bulk_email_tenant_01.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

	public static final UniqueKey<CampaignsRecord> KEY_CAMPAIGNS_PRIMARY = Internal.createUniqueKey(Campaigns.CAMPAIGNS, DSL.name("KEY_campaigns_PRIMARY"), new TableField[] { Campaigns.CAMPAIGNS.ID }, true);
   
    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

}
