/*
 * This file is generated by jOOQ.
 */
package com.mt.quarkus.model;

import com.mt.quarkus.model.tables.Campaigns;

/**
 * Convenience access to all tables in bulk_email_tenant_01.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table <code>bulk_email_tenant_01.campaigns</code>.
	 */
	public static final Campaigns CAMPAIGNS = Campaigns.CAMPAIGNS;

}
